# Generated by Django 4.0.1 on 2022-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centretype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='centretype',
            name='subtype',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
