# Generated by Django 4.0.1 on 2022-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_centretype_description_alter_centretype_subtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='centre',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='centre',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='gov_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='governing body id'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='pupil_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of pupils'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
