# Generated by Django 4.0.1 on 2022-01-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_country_options_alter_centre_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='p_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.address', verbose_name='primary address'),
        ),
        migrations.AddField(
            model_name='centre',
            name='p_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.email', verbose_name='primary email'),
        ),
        migrations.AddField(
            model_name='centre',
            name='p_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.centrecontactperson', verbose_name='primary contact person'),
        ),
        migrations.AddField(
            model_name='centre',
            name='p_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.phone', verbose_name='primary phone'),
        ),
        migrations.DeleteModel(
            name='CentrePrimaryContact',
        ),
    ]
