# Generated by Django 4.0.1 on 2022-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_centrecontactperson_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='p_address',
        ),
        migrations.AddField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, verbose_name='city / suburb / local area'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200, verbose_name='state / district / region'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('centre', 'primary_address')},
        ),
    ]
