# Generated by Django 4.0.1 on 2022-01-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_centre_p_address_address_primary_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrecontactperson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='centre',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='p_person',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='p_phone',
        ),
        migrations.AddField(
            model_name='address',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrecontactperson',
            name='primary_contact',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='email',
            name='primary_email',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='primary_phone',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='centrecontactperson',
            unique_together={('centre', 'contact_person', 'primary_contact')},
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('centre', 'primary_email')},
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('centre', 'primary_phone')},
        ),
    ]
