# Generated by Django 4.0.1 on 2022-01-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_centre_contact_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='contact_persons',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', related_query_name='contact_person', to='leads.centre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactperson',
            name='primary_contact',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('centre', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together={('centre', 'primary_contact')},
        ),
        migrations.DeleteModel(
            name='CentreContactPerson',
        ),
        migrations.RemoveField(
            model_name='address',
            name='primary_address',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='slug',
        ),
    ]
