# Generated by Django 4.0.1 on 2022-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_centre_contact_persons_contactperson_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='primary_contact',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='primary_email',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='primary_phone',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
