# Generated by Django 4.0.1 on 2022-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_contactperson_primary_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='gov_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='governing body id'),
        ),
    ]
