# Generated by Django 4.0.1 on 2022-02-03 00:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_primary_contact_contactperson_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='area_code',
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
