# Generated by Django 4.0.1 on 2022-02-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_phone_area_code_alter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
