# Generated by Django 4.0.1 on 2022-02-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_addresstype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.datasource'),
            preserve_default=False,
        ),
    ]
