# Generated by Django 4.0.1 on 2022-02-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_centregroup_centre_group'),
        ('leads', '0015_openinghours_source'),
    ]

    operations = [
    ]
