# Generated by Django 4.0.1 on 2022-02-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_merge_20220204_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'governing body',
                'verbose_name_plural': 'governing bodies',
            },
        ),
        migrations.AddField(
            model_name='centregroup',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centre',
            name='gov_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='governing body id'),
        ),
        migrations.AddField(
            model_name='centre',
            name='gov_body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='centres', related_query_name='centre', to='leads.govbody', verbose_name='governing body'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='centre',
            unique_together={('gov_id', 'gov_body')},
        ),
    ]
