# Generated by Django 4.0.1 on 2022-03-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_centre_google_place_id_alter_centre_gov_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
