# Generated by Django 4.0.1 on 2022-01-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0010_alter_contactperson_primary_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('documentation', models.TextField()),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrapers', related_query_name='scraper', to='leads.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.centre')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.scraper')),
            ],
            options={
                'unique_together': {('scraper', 'centre')},
            },
        ),
    ]
