# Generated by Django 4.0.1 on 2022-01-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapequeue',
            name='priority',
            field=models.CharField(choices=[('hi', 'High'), ('mo', 'Moderate'), ('lo', 'Low')], default='mo', max_length=2),
            preserve_default=False,
        ),
    ]
